/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UneteAlEquipoRouteImport } from './routes/unete-al-equipo'
import { Route as RestauranteRouteImport } from './routes/restaurante'
import { Route as ReservasRouteImport } from './routes/reservas'
import { Route as EventosRouteImport } from './routes/eventos'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as CartaRouteImport } from './routes/carta'
import { Route as CajaRouteImport } from './routes/caja'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'

const UneteAlEquipoRoute = UneteAlEquipoRouteImport.update({
  id: '/unete-al-equipo',
  path: '/unete-al-equipo',
  getParentRoute: () => rootRouteImport,
} as any)
const RestauranteRoute = RestauranteRouteImport.update({
  id: '/restaurante',
  path: '/restaurante',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservasRoute = ReservasRouteImport.update({
  id: '/reservas',
  path: '/reservas',
  getParentRoute: () => rootRouteImport,
} as any)
const EventosRoute = EventosRouteImport.update({
  id: '/eventos',
  path: '/eventos',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const CartaRoute = CartaRouteImport.update({
  id: '/carta',
  path: '/carta',
  getParentRoute: () => rootRouteImport,
} as any)
const CajaRoute = CajaRouteImport.update({
  id: '/caja',
  path: '/caja',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/caja': typeof CajaRoute
  '/carta': typeof CartaRoute
  '/contacto': typeof ContactoRoute
  '/eventos': typeof EventosRoute
  '/reservas': typeof ReservasRoute
  '/restaurante': typeof RestauranteRoute
  '/unete-al-equipo': typeof UneteAlEquipoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/caja': typeof CajaRoute
  '/carta': typeof CartaRoute
  '/contacto': typeof ContactoRoute
  '/eventos': typeof EventosRoute
  '/reservas': typeof ReservasRoute
  '/restaurante': typeof RestauranteRoute
  '/unete-al-equipo': typeof UneteAlEquipoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/caja': typeof CajaRoute
  '/carta': typeof CartaRoute
  '/contacto': typeof ContactoRoute
  '/eventos': typeof EventosRoute
  '/reservas': typeof ReservasRoute
  '/restaurante': typeof RestauranteRoute
  '/unete-al-equipo': typeof UneteAlEquipoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/caja'
    | '/carta'
    | '/contacto'
    | '/eventos'
    | '/reservas'
    | '/restaurante'
    | '/unete-al-equipo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/caja'
    | '/carta'
    | '/contacto'
    | '/eventos'
    | '/reservas'
    | '/restaurante'
    | '/unete-al-equipo'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/caja'
    | '/carta'
    | '/contacto'
    | '/eventos'
    | '/reservas'
    | '/restaurante'
    | '/unete-al-equipo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CajaRoute: typeof CajaRoute
  CartaRoute: typeof CartaRoute
  ContactoRoute: typeof ContactoRoute
  EventosRoute: typeof EventosRoute
  ReservasRoute: typeof ReservasRoute
  RestauranteRoute: typeof RestauranteRoute
  UneteAlEquipoRoute: typeof UneteAlEquipoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unete-al-equipo': {
      id: '/unete-al-equipo'
      path: '/unete-al-equipo'
      fullPath: '/unete-al-equipo'
      preLoaderRoute: typeof UneteAlEquipoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurante': {
      id: '/restaurante'
      path: '/restaurante'
      fullPath: '/restaurante'
      preLoaderRoute: typeof RestauranteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservas': {
      id: '/reservas'
      path: '/reservas'
      fullPath: '/reservas'
      preLoaderRoute: typeof ReservasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eventos': {
      id: '/eventos'
      path: '/eventos'
      fullPath: '/eventos'
      preLoaderRoute: typeof EventosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carta': {
      id: '/carta'
      path: '/carta'
      fullPath: '/carta'
      preLoaderRoute: typeof CartaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/caja': {
      id: '/caja'
      path: '/caja'
      fullPath: '/caja'
      preLoaderRoute: typeof CajaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CajaRoute: CajaRoute,
  CartaRoute: CartaRoute,
  ContactoRoute: ContactoRoute,
  EventosRoute: EventosRoute,
  ReservasRoute: ReservasRoute,
  RestauranteRoute: RestauranteRoute,
  UneteAlEquipoRoute: UneteAlEquipoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
